[versions]
assertj-ver = "3.24.2"
avro-ver = "1.11.3"
awaitility-ver = "4.2.0"
bson-ver = "4.11.0"
embeddedkafka-ver = "3.8.0"
hadoop-ver = "3.4.0"
hive-ver = "2.3.9"
http-client-ver = "5.2.1"
iceberg-ver = "1.6.1"
jackson-ver = "2.14.2"
junit-ver = "5.11.1"
kafka-ver = "3.8.0"
logback-ver = "1.5.8"
minio-ver = "8.5.12"
mockito-ver = "4.2.0"
parquet-ver = "1.14.3"
slf4j-ver = "1.7.36"
testcontainers-ver = "1.20.3"



[libraries]
avro = { module = "org.apache.avro:avro", version.ref = "avro-ver" }
bson = { module = "org.mongodb:bson", version.ref = "bson-ver"}
hadoop-client = { module = "org.apache.hadoop:hadoop-client", version.ref = "hadoop-ver" }
hadoop-common = { module = "org.apache.hadoop:hadoop-common", version.ref = "hadoop-ver" }
hive-metastore = { module = "org.apache.hive:hive-metastore", version.ref = "hive-ver" }
iceberg-api = { module = "org.apache.iceberg:iceberg-api", version.ref = "iceberg-ver" }
iceberg-aws = { module = "org.apache.iceberg:iceberg-aws", version.ref = "iceberg-ver" }
iceberg-aws-bundle = { module = "org.apache.iceberg:iceberg-aws-bundle", version.ref = "iceberg-ver" }
iceberg-azure = { module = "org.apache.iceberg:iceberg-azure", version.ref = "iceberg-ver" }
iceberg-azure-bundle = { module = "org.apache.iceberg:iceberg-azure-bundle", version.ref = "iceberg-ver" }
iceberg-common = { module = "org.apache.iceberg:iceberg-common", version.ref = "iceberg-ver" }
iceberg-core = { module = "org.apache.iceberg:iceberg-core", version.ref = "iceberg-ver" }
iceberg-data = { module = "org.apache.iceberg:iceberg-data", version.ref = "iceberg-ver" }
iceberg-gcp = { module = "org.apache.iceberg:iceberg-gcp", version.ref = "iceberg-ver" }
iceberg-gcp-bundle = { module = "org.apache.iceberg:iceberg-gcp-bundle", version.ref = "iceberg-ver" }
iceberg-guava = { module = "org.apache.iceberg:iceberg-bundled-guava", version.ref = "iceberg-ver" }
iceberg-hive-metastore = { module = "org.apache.iceberg:iceberg-hive-metastore", version.ref = "iceberg-ver" }
iceberg-kafka-connect-events = {module = "org.apache.iceberg:iceberg-kafka-connect-events", version.ref = "iceberg-ver"}
iceberg-nessie = { module = "org.apache.iceberg:iceberg-nessie", version.ref = "iceberg-ver" }
iceberg-orc = { module = "org.apache.iceberg:iceberg-orc", version.ref = "iceberg-ver" }
iceberg-parquet = { module = "org.apache.iceberg:iceberg-parquet", version.ref = "iceberg-ver" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson-ver" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-ver" }
kafka-clients = { module = "org.apache.kafka:kafka-clients", version.ref = "kafka-ver" }
kafka-connect-api = { module = "org.apache.kafka:connect-api", version.ref = "kafka-ver" }
kafka-connect-json = { module = "org.apache.kafka:connect-json", version.ref = "kafka-ver" }
kafka-connect-transforms = { module = "org.apache.kafka:connect-transforms", version.ref = "kafka-ver" }
kafka-storage = { module = "org.apache.kafka:kafka-storage", version.ref = "kafka-ver" }
kafka-storage-api = { module = "org.apache.kafka:kafka-storage-api", version.ref = "kafka-ver" }
parquet-avro = { module = "org.apache.parquet:parquet-avro", version.ref = "parquet-ver" }
parquet-column = { module = "org.apache.parquet:parquet-column", version.ref = "parquet-ver" }
parquet-common = { module = "org.apache.parquet:parquet-common", version.ref = "parquet-ver" }
parquet-hadoop = { module = "org.apache.parquet:parquet-hadoop", version.ref = "parquet-ver" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-ver" }

# test dependencies
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj-ver" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility-ver" }
embeddedkafka =  { module = "io.github.embeddedkafka:embedded-kafka_3", version.ref = "embeddedkafka-ver" }
http-client = { module =  "org.apache.httpcomponents.client5:httpclient5", version.ref = "http-client-ver" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-ver" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit-ver" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-ver" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit-ver" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback-ver" }
minio = {module = "io.minio:minio", version.ref = "minio-ver" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito-ver" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers-ver" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers-ver" }
testcontainers-minio = { module = "org.testcontainers:minio", version.ref = "testcontainers-ver" }
testcontainers-kafka = { module = "org.testcontainers:kafka", version.ref = "testcontainers-ver" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers-ver" }

spotless-gradle = "com.diffplug.spotless:spotless-plugin-gradle:6.13.0"
palantir-gradle = "com.palantir.baseline:gradle-baseline-java:4.42.0"

[bundles]
iceberg = ["iceberg-api", "iceberg-common", "iceberg-core", "iceberg-data", "iceberg-guava", "iceberg-orc", "iceberg-parquet", "iceberg-kafka-connect-events"]
iceberg-ext = ["iceberg-aws", "iceberg-aws-bundle", "iceberg-azure", "iceberg-azure-bundle", "iceberg-gcp", "iceberg-gcp-bundle", "iceberg-nessie"]
parquet = ["parquet-avro", "parquet-column", "parquet-common", "parquet-hadoop"]
testcontainers = ["testcontainers", "testcontainers-minio", "testcontainers-kafka", "testcontainers-junit", "testcontainers-bom"]


[plugins]
nebula-release = "nebula.release:17.2.2"
